name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"           # julkistetaan repon juuresta (admin/, public/, device/)
          api_location: ""            # ei SWA:n omaa APIa
          output_location: ""         # ei build-kansiota
          skip_app_build: true        # ei npm buildia (meillä pelkät staattiset tiedostot)
          deployment_action: "upload" # <-- TÄMÄ KORJAA VIRHEEN
