name: Build & Deploy (.NET 8 → Azure Web App, OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: lipunryosto-api
  AZURE_RESOURCE_GROUP: rg-lipunryosto-prod
  DOTNET_VERSION: 8.0.x

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OS deps (OpenSSL + zip)
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl3 zip

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ./src/Lipunryosto.Api/Lipunryosto.Api.csproj

      - name: Publish
        run: dotnet publish ./src/Lipunryosto.Api/Lipunryosto.Api.csproj -c Release -o "${{ github.workspace }}/publish"

      - name: List publish output
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la "${{ github.workspace }}"
          echo "Publish dir:"
          ls -la "${{ github.workspace }}/publish"

      - name: Zip package
        run: |
          cd "${{ github.workspace }}/publish"
          zip -r ../package.zip .

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App (zip)
        run: |
          az webapp deploy \
            --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
            --name "${{ env.AZURE_WEBAPP_NAME }}" \
            --src-path "${{ github.workspace }}/package.zip" \
            --type zip
