name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"              # repon juuresta (tai esim. "frontend")
          api_location: ""               # tyhjä, koska API on App Servicessä
          output_location: ""            # tyhjä -> ei build-kansiota
          skip_app_build: true           # ← TÄRKEÄ: ei yritetä ajaa npm buildia
